const PRODUCT_CONFIG = {
  id: "bolso-impermeable",
  origin: "landing_bolso_impermeable",
  category: "Bolsos",
  name: "Bolso de Viaje Expandible Impermeable",
  shortName: "Bolso Expandible",
  price: 219000,
  oldPrice: 300000,
  combo2: 405000,
  combo3: 575000,
  currency: "PYG",
  benefit: "Más capacidad, más orden y menos preocupaciones en cada viaje.",
  buttonText: "Reservar mi bolso ahora",
  checkoutTitle: "Un paso más para recibir tu pedido",
  metaTitle: "Bolso de Viaje Expandible Impermeable | VG Shop Py",
  metaDescription: "Bolso de viaje expandible e impermeable con separación húmedo/seco y compartimento para calzado. Envío gratis a Asunción y Central y pago al recibir.",
  heroTitle: "Bolso de Viaje Expandible Impermeable",
  heroSubtitle: "Ideal para viajes, gimnasio y escapadas. Base expandible que suma hasta 12 cm de capacidad, bolsillo húmedo/seco, compartimento para calzado y tela Oxford impermeable.",
  colors: ["Rosa", "Lila", "Gris"],
  images:{
    hero:"img/PROD20260423_69ea3f74e8023.jpg",
    banner:"img/rosa.jpeg",
    img1:"img/PROD20260423_69ea3f74e8023.jpg",
    img2:"img/rosa.jpeg",
    img3:"img/Lila.jpeg",
    img4:"img/Gris.jpg"
  },
  supabaseUrl: 'https://roruinqorwgolcrhhmpm.supabase.co',
  supabaseAnonKey: 'sb_publishable_aRPb1yNunMEheat00BxwtQ_Uft732KJ',
  supabaseTable: 'pedidos_web',
};
